title: EEB-2245/W
author: University of Connecticut
email: evolution@uconn.edu
description: >- # this means to ignore newlines until "baseurl:"
 Course web site for Spring semester 2021  
baseurl: "/"
#baseurl: "/evolution"
#url: "http://uconneeb.github.io"
markdown: kramdown
theme: minima
exclude: [
        'image-links.md',
        'applets/correlation/',
        'applets/sweep/',
        'applets/biston-early/',
        'applets/biston-late/',
        'applets/sweep/',
        'applets/selfing/',
        'applets/dpp/',
        'applets/ou/',
        'applets/pagel/'
    ]
header_pages:
  - schedule.md
  - grading.md
  - applets.md
  - exam_review.md
  - biblio.md
  - contact.md
plugins:
  - jekyll-seo-tag