title: EEB-2245
author: University of Connecticut
email: evolution@uconn.edu
description: >- # this means to ignore newlines until "baseurl:"
 Course web site for EEB 2245 (Evolution), Spring semester 2019  
baseurl: "/evolution"
url: "http://uconneeb.github.io"
markdown: kramdown
theme: minima
