title: EEB-2245/2245W
author: University of Connecticut
email: evolution@uconn.edu
description: >- # this means to ignore newlines until "baseurl:"
 Course web site for Spring semester 2019  
baseurl: "/evolution"
url: "http://uconneeb.github.io"
markdown: kramdown
theme: minima
exclude: ['04-applets.md','applets/ball-drop.md']
header_pages:
  - 01-schedule.md
  - 02-grading.md
  - 05-review-sessions.md
  - 03-contact.md
